# Generated by Django 5.2.3 on 2025-06-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bvn',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nin',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
